---
title: "CCMnet: Edge Models"
author: "Your Name"
output:
  rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{CCMnet Examples}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# CCMnet Examples: Edge

```{r setup, include=FALSE}
# Set global chunk options
knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE,
  fig.width = 6,
  fig.height = 4
)

# Load libraries
library(CCMnetpy)
library(tidyverse)
library(igraph)
library(reticulate)

# -----------------------------
# Python setup for CCMnet
# -----------------------------

# Check if the environment exists
env_name <- "r-ccmnet" #"ccmnet_env"

if (!env_name %in% reticulate::virtualenv_list() &&
    !env_name %in% reticulate::conda_list()$name) {
  message("CCMnet Python environment not found. Please run install_ccmnet() first. Here is an example of the command: install_ccmnet(envname = env_name, python_version = NULL, restart_session = FALSE)")
}

# Use the environment
reticulate::use_virtualenv(env_name, required = TRUE)

# Initialize CCMnet Python backend
CCMnet_python_setup()
```

# Example 1: Poisson

```{r edge-example-poisson}

population <- 100
covPattern <- rep(0L, population)

# Run CCMnet MCMC
fit <- CCM_fit(
  Network_stats = list("Edge"),
  Prob_Distr = list("Poisson"),
  Prob_Distr_Params = list(6.192894),
  population = population,
  covPattern = covPattern
)

# Add theoretical distribution
fit <- CCM_theoretical_check(fit,
                             n_sim = nrow(fit$mcmc_stats))

# Plots
plot(fit, stats = "edges", type = "density", include_theoretical = TRUE)
```

# Example 2: Uniform

```{r edge-example-uniform}

population <- 10
covPattern <- rep(0L, population)

# Run CCMnet MCMC
fit <- CCM_fit(
  Network_stats = list("Edge"),
  Prob_Distr = list("uniform"),
  Prob_Distr_Params = NULL,
  population = population,
  covPattern = covPattern
)

# Add theoretical distribution
fit <- CCM_theoretical_check(fit,
                             n_sim = nrow(fit$mcmc_stats))

# Plots
plot(fit, stats = "edges", type = "density", include_theoretical = TRUE)
```

# Example 3: Non-Parametric

```{r edge-example-NP}

population <- 100
covPattern <- rep(0L, population)

Prob_Distr_Params_P1 = dpois(0:choose(population,2), lambda = 5)
Prob_Distr_Params_P2 = dpois(0:choose(population,2), lambda = 10)
Prob_Distr_Params_C = Prob_Distr_Params_P1 + Prob_Distr_Params_P2
Prob_Distr_Params_C = Prob_Distr_Params_C/sum(Prob_Distr_Params_C)

# Run CCMnet MCMC
fit <- CCM_fit(
  Network_stats = list("Edge"),
  Prob_Distr = list("NP"),
  Prob_Distr_Params = list(Prob_Distr_Params_C),
  population = population,
  covPattern = covPattern,
  samplesize = 10000L
)

# Add theoretical distribution
fit <- CCM_theoretical_check(fit,
                             n_sim = nrow(fit$mcmc_stats))

# Plots
plot(fit, stats = "edges", type = "density", include_theoretical = TRUE)
```

