---
title: "CCMnet: Edge, Degree, Mixing, and Structural Assessment"
author: "Ravi Goyal"
output:
  rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{CCMnet Combined Examples}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
# Set global chunk options
knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE,
  fig.width = 6,
  fig.height = 4
)

# Load libraries
library(CCMnetpy)
library(tidyverse)
library(igraph)
library(reticulate)
library(mvtnorm)
# -----------------------------
# Python setup for CCMnet
# -----------------------------

env_name <- "r-ccmnet"

if (!env_name %in% reticulate::virtualenv_list() &&
    !env_name %in% reticulate::conda_list()$name) {
  message("CCMnet Python environment not found. Please run install_ccmnet() first. Here is an example of the command: install_ccmnet(envname = env_name, python_version = NULL, restart_session = FALSE)")
}

reticulate::use_virtualenv(env_name, required = TRUE)

CCMnet_python_setup()
```

```{r degmix_clustering-example-normal_debug1}
Prob_Distr_Params_1 = rep(0, 4950)
Prob_Distr_Params_1[1] = 5
Prob_Distr_Params_1[2] = 25
Prob_Distr_Params_1[100] = 50
 
Prob_Distr_Params_2 = matrix(0, nrow = 4950, ncol = 4950)
diag(Prob_Distr_Params_2) = rep(2000, 4950)
Prob_Distr_Params_2[1,1] = .3
Prob_Distr_Params_2[2,2] = .3  
Prob_Distr_Params_2[100,100] = .3
 
Prob_Distr_Params_degmix <- list(
  Prob_Distr_Params_1,
  Prob_Distr_Params_2
)

population <- 100
covPattern <- rep(0L, population)


out <- CCMnetpy::CCMnet_constr(
    Network_stats = list("degmix"),
    Prob_Distr = list("Multivariate_normal"),
    Prob_Distr_Params = Prob_Distr_Params_degmix,
    samplesize = as.integer(10),
    burnin = as.integer(1),
    interval = as.integer(1),
    statsonly = TRUE,
    G = NULL,
    P = NULL,
    population = as.integer(population),
    covPattern = as.integer(covPattern),
    bayesian_inference = FALSE,
    Ia = NULL,
    Il = NULL,
    R = NULL,
    epi_params = NULL,
    print_calculations = TRUE,
    use_G = FALSE,
    outfile = "none",
    partial_network = as.integer(FALSE),
    obs_nodes = NULL,
    MH_proposal_type = "TNT",
    Obs_stats = NULL
  )
```

```{r degmix_clustering-example-normal_debug2}
Prob_Distr_Params_1 = rep(0, 4950)
Prob_Distr_Params_1[1] = 5
Prob_Distr_Params_1[2] = 25
Prob_Distr_Params_1[100] = 50
 
Prob_Distr_Params_2 = matrix(0, nrow = 4950, ncol = 4950)
diag(Prob_Distr_Params_2) = rep(2000, 4950)
Prob_Distr_Params_2[1,1] = .3
Prob_Distr_Params_2[2,2] = .3  
Prob_Distr_Params_2[100,100] = .3
 
Prob_Distr_Params_degmix <- list(
  Prob_Distr_Params_1,
  Prob_Distr_Params_2
)

Prob_Distr_Params_clustering <- list(
  6,
  2
)

Prob_Distr_Params = list(Prob_Distr_Params_degmix,
                         Prob_Distr_Params_clustering)

population <- 100
covPattern <- rep(0L, population)


out <- CCMnetpy::CCMnet_constr(
    Network_stats = list("degmix_clustering"),
    Prob_Distr = list("Multivariate_normal", "Normal"),
    Prob_Distr_Params = Prob_Distr_Params,
    samplesize = as.integer(100),
    burnin = as.integer(1),
    interval = as.integer(1),
    statsonly = TRUE,
    G = NULL,
    P = NULL,
    population = as.integer(population),
    covPattern = as.integer(covPattern),
    bayesian_inference = FALSE,
    Ia = NULL,
    Il = NULL,
    R = NULL,
    epi_params = NULL,
    print_calculations = TRUE,
    use_G = FALSE,
    outfile = "none",
    partial_network = as.integer(FALSE),
    obs_nodes = NULL,
    MH_proposal_type = "TNT",
    Obs_stats = NULL
  )
```

```{r degmix_clustering-example-normal}

Prob_Distr_Params_1 = rep(0, 4950)
Prob_Distr_Params_1[1] = 5
Prob_Distr_Params_1[2] = 25
Prob_Distr_Params_1[100] = 50
 
Prob_Distr_Params_2 = matrix(0, nrow = 4950, ncol = 4950)
diag(Prob_Distr_Params_2) = rep(2000, 4950)
Prob_Distr_Params_2[1,1] = .3
Prob_Distr_Params_2[2,2] = .3  
Prob_Distr_Params_2[100,100] = .3
 
Prob_Distr_Params_degmix <- list(
  Prob_Distr_Params_1,
  Prob_Distr_Params_2
)

Prob_Distr_Params_clustering <- list(
  6,
  2
)

Prob_Distr_Params = list(Prob_Distr_Params_degmix,
                         Prob_Distr_Params_clustering)

population <- 100
covPattern <- rep(0L, population)

fit <- CCM_fit(
  Network_stats = list("degmix_clustering"),
  Prob_Distr = list("Multivariate_normal", "Normal"),
  Prob_Distr_Params = Prob_Distr_Params,
  population = population,
  covPattern = covPattern,
  samplesize = 1000L,
  burnin = 2000L,
  interval = 100L,
)


# Compare MCMC samples to theoretical Poisson distribution
fit <- CCM_theoretical_check(fit, n_sim = nrow(fit$mcmc_stats))

# Plot density with theoretical distribution
plot(fit, stats = c("DM11", "DM21", "DM22", "triangles"), type = "density", include_theoretical = TRUE)

```


