---
title: "CCMnet: Partial Network Bayesian Inference"
author: "Your Name"
output:
  rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{CCMnet Partial Network}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}

# Set global chunk options
knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE,
  fig.width = 6,
  fig.height = 4
)

# Load libraries
library(CCMnetpy)
library(tidyverse)
library(igraph)

```


# Generate a Partially Observed Network

```{r generate-partial-network}
# Set parameters 

population <- 100
sample_fraction <- 0.8
covPattern <- rep(0, population) # Example covariate pattern
Network_stats <- list("Degree")
Prob_Distr <- list("DirMult")
Prob_Distr_Params <- list(list(c(2,21,15,12)))


# Generate the partial network
partial_net <- generate_partial_network(
  population = population,
  sample_fraction = sample_fraction,
  Network_stats = Network_stats,
  Prob_Distr = Prob_Distr,
  Prob_Distr_Params = Prob_Distr_Params,
  covPattern = covPattern
)


# Extract results
g_obs <- partial_net$g_obs
g_truth <- partial_net$g_truth
sample_ids <- partial_net$sample_ids
G_stats_truth <- partial_net$G_stats_truth


# Summary
cat("Number of observed nodes:", length(sample_ids), "\n")
cat("Number of edges in observed network:", igraph::gsize(g_obs), "\n")
```

# Run CCM Missing Data Inference (MCMC)

```{r run-mcmc}
# MCMC parameters
n_mcmc_trials <- 10
MCMC_wgt <- 1

mcmc_result <- CCM_MissingInference(
  g_obs = g_obs,
  sample_ids = sample_ids,
  Network_stats = Network_stats,
  Prob_Distr = Prob_Distr,
  Prob_Distr_Params = Prob_Distr_Params,
  Prob_Distr_Params_prior = list(
    "Dirichlet_Gamma",
    c(1, population),
    rep(1/(population*10000), population)
  ),
  covPattern = covPattern,
  population = population,
  n_mcmc_trials = n_mcmc_trials,
  MCMC_wgt = MCMC_wgt
)


```

# Compare True vs Posterior Network Statistics

```{r compare-stats} 

#Trace plots
CCM_traceplot(mcmc_result, stats = paste0("deg", 0:9))

# Plot posterior distribution of degrees vs true
CCM_compare_stats(
  result = mcmc_result,
  G_stats_truth = partial_net$G_stats_truth,
  stats = paste0("deg", 0:9)
)

# Distance calculation

truth_df = G_stats_truth %>%
  pivot_longer(everything(), names_to = "stat")

mcmc_result$G_stats.df %>% 
  pivot_longer(everything(), names_to = "stat") %>%
  group_by(stat) %>%
  summarise(mean_count = mean(value)) %>%
  mutate(est_prop = mean_count/population) %>%
  left_join(truth_df, by = "stat") %>%
  mutate(true_prop = value/population) %>%
  mutate(hellinger_dist_ind = (sqrt(est_prop) - sqrt(true_prop))^2) %>%
  pull(hellinger_dist_ind) %>%
  sum() %>% sqrt() * 1/sqrt(2)

```